README.md, ckanext/data_qld/ckan_dataset.json, ckanext/data_qld/constants.py, ckanext/data_qld/controller.py, ckanext/data_qld/google_analytics/__init__.py, ckanext/data_qld/google_analytics/capture_api_actions.json, ckanext/data_qld/google_analytics/controller.py, ckanext/data_qld/google_analytics/plugin.py, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/presets.json, ckanext/data_qld/templates/admin/config.html, ckanext/data_qld/templates/emails/subjects/close_datarequest_creator.txt, ckanext/data_qld/templates/emails/subjects/new_datarequest_organisation.txt, ckanext/data_qld/templates/emails/subjects/open_datarequest_creator.txt, ckanext/data_qld/templates/emails/subjects/open_datarequest_organisation.txt, setup.py
This PR contains updates for the following Jira stories:
- DQL-32 - Google Analytics - API call event tracking
- DQL-55 - Bug: CKAN Sysadmin unable to update Config
- DQL-27 - Data Base & Form updates
- DQL-39 - Data Requests - Ability to Re-open Data Request
- DQL-19 - Modify CKAN dataset schema
Please note: Some updates for these stories will already exist in the `develop` branch as at the point it was branched to `training`.
=> Training updates

README.md, ckanext/data_qld/integration_plugin.py, ckanext/data_qld/plugin.py, ckanext/data_qld/resources_plugin.py, setup.py
- New 'data_qld_resources' plugin should be used when we don't want integration with third party extensions.
- Still need to retain the split between datarequest_auth and generic auth
=> [QOL-5834] revert most changes to standard plugin

ckanext/data_qld/helpers.py, ckanext/data_qld/integration_plugin.py, ckanext/data_qld/plugin.py
- [DQL2-24] Refactored get_datarequest_comments_badge to get_content_type_comments_badge so it can be used for different content_types
- [DQL2-24] Removed comment badge helpers and moved them into ytp-comments
=> [DQL-188] EPIC - Dataset comment enhancements

ckanext/data_qld/resources_plugin.py, ckanext/data_qld/templates/emails/bodies/new_datarequest_organisation.txt, setup.py
This PR contains changes for the following stories:
[[DQL2-30]](https://salsadigital.atlassian.net/browse/DQL2-30) Email notification content enhancements:
- Updated new_datarequest_organisation email template
[[DQL2-31]](https://salsadigital.atlassian.net/browse/DQL2-31)Close data request Circumstances enhancements
- Added 'close_circumstance' & 'approx_publishing_date' to 'close_datarequest' action
- On 'open_datarequest' set 'close_circumstance' & 'approx_publishing_date' to None
- Updated 'config.feature' as the "Data Request Config" has been removed
@duttonw & @ThrawnCA for your review.
=> [DQL-204] Enhancements to the data request functionality

ckanext/data_qld/controller.py, ckanext/data_qld/plugin.py, test/features/login_redirect.feature
This PR fixes an issue with the pagination on the dataset listing pages / search by adjusting the `/dataset/{action}` route controller.
@duttonw & @ThrawnCA - for review please.
=> [DQL2-21] Fix search pagination

ckanext/data_qld/reporting/constants.py, ckanext/data_qld/reporting/controller.py
This PR addresses two issues:
1. Converting `.ini` configuration settings for `ckan.reporting.datarequest_open_max_days` and `ckan.reporting.comment_no_reply_max_days` to INT before usage
2. Pre-populating the start and end date of the report to the defaults
@duttonw & @ThrawnCA - for review please
=> [DQL-211] Reporting fixes

.docker/scripts/create-test-data.sh, .docker/scripts/init-ext.sh, .docker/scripts/init.sh, .docker/test.ini, ckanext/data_qld/reporting/helpers/helpers.py, ckanext/data_qld/templates/reporting/index.html, requirements-dev.txt, test/features/environment.py, test/features/reporting.feature, test/features/steps/steps.py
- Added data request and ytp-comments config settings
- Created test data for data request
- Fixed issue with end_date on report not using ckan display timezone
- Added element ids to use for reporting testing
- Added new BDD steps for data requests, comments and reporting
- Added new reporting.feature for BDD tests
- Removed odi-certificate extension dependency
- Adding ytp-comments extension and dependencies for BDD tests
- Added extension data request and created test data and steps
@duttonw @ThrawnCA Here are the BDD tests for your review.
=> [DQL2-35] Reporting Automated testing considerations

ckanext/data_qld/resource_freshness/helpers/helpers.py, ckanext/data_qld/resource_freshness/validation.py
Hi @duttonw @ThrawnCA ,
Here is the PR for the following stories.
[Enable package_patch API call to handle "Nature of change to data" mandatory requirement](https://salsadigital.atlassian.net/browse/DQL3-63)
- Added logic to check user access to display `nature_of_change`
- This should fix the datastore issue which uses package_patch
[Handle resource validation for existing datasets when the user changes metadata without updating data](https://salsadigital.atlassian.net/browse/DQL3-75)
- Added logic to calculate `next_update_due` if there is no current value set
=> UAT remediation [DQL3-63][DQL3-75]

ckanext/data_qld/resource_freshness/helpers/helpers.py
Hi @duttonw ,
Here is the fix for manually submitting a resource to the datastore.
There was a bug in the resource data updated logic which caused a downstream validator to trigger the missing 'nature_of_change' error message which was not required.
=> Xloader datastore fix

ckanext/data_qld/templates/scheming/package/read.html
- there's no consistent named route, so we need different names for CKAN 2.8 and 2.9
=> [QOL-7939] fix breadcrumb link to organisation index page

ckanext/data_qld/dataset_deletion/helpers.py, ckanext/data_qld/plugin.py
Hi @duttonw @ThrawnCA ,
I am not sure if you guys are aware but I noticed in our QA environment the `package_delete` API is broken and throwing a `*** AttributeError: 'CSRFAwareRequest' object has no attribute 'body'` error in the deletion reason helper `add_deletion_of_dataset_reason` on line 14 `body = json.loads(request.body)`
I am not sure when the body attribute was removed from the request object but I have refactored the code with a different approach to not rely on the request object for the API.
Initially, this helper was called from the `IPackageContoller` interface `delete` which only has the package entity object.
This has been updated to use another interface `after_delete` with the `data_dict` as a parameter with the `deletion_reason` data we require.
I also refactored some …
=> Package delete API issue with deletion reason

.docker/scripts/create-test-data.sh, .env, .github/workflows/test.yml, docker-compose.yml, requirements-dev.txt, test/features/comments.feature, test/features/data_qld_theme.feature, test/features/data_request.feature, test/features/data_validation.feature, test/features/de_identified_data.feature, test/features/engagement_reporting.feature, test/features/google_analytics.feature, test/features/groups.feature, test/features/homepage.feature, test/features/login_redirect.feature, test/features/navigation.feature, test/features/organisations.feature, test/features/resource_availability.feature, test/features/resource_freshness.feature, test/features/schema_metadata.feature, test/features/steps/steps.py, test/features/user_creation.feature, test/features/users.feature
- Use fixed CKAN core version in tests
- Update ckanext-qgov test version
- Reduce dependency on in-browser test setup
- Point unnecessary third-party domains at localhost during tests for faster resolution
=> QOL-8842 test cleanup

ckanext/data_qld/helpers.py, ckanext/data_qld/resource_freshness/validation.py
- the 'reorder' APIs don't change any actual values, so they shouldn't require a reason to be specified
=> [DC-31529] ignore 'reorder' APIs when validating mandatory fields

ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, test/features/resource_freshness.feature, test/features/steps/steps.py
Background jobs have already been fixed so that they don't fail validation, but they also need to be adjusted so that they don't overwrite nature_of_change with a blank.
=> DC-31541 Don't overwrite nature_of_change in background jobs

ckanext/data_qld/blueprints.py, ckanext/data_qld/templates/robots.txt, test/features/data_qld_theme.feature
- CKAN 2.9 reverted to serving it from the 'public' directory, but we want Jinja syntax,
so instead we add a Flask blueprint rule to render it
=> [QOL-8988] add our custom robots.txt file

ckanext/data_qld/plugin.py
- IPackageController and IResourceController both define after_delete, we only want the package one
=> [QOL-9055] handle after_delete coming from multiple interfaces

.docker/Dockerfile-template.ckan
To add an exception for this directory, call:
git config --global --add safe.directory /srv/app/src/ckan
This is on the 2.9 py3 container image at this time.
=> fix fatal: detected dubious ownership in repository at '/srv/app/src/ckan

.circleci/build.sh, .docker/ckan.ini, .github/workflows/test.yml, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/header.html, ckanext/data_qld/templates/user/dashboard.html, docker-compose.yml, extensions.txt
- News feeds have now moved to ckanext-activity, which is provided but not enabled out of the box. With the extension enabled, the route is 'activity.dashboard'; without it, the appropriate route is the dataset page, 'dashboard.datasets'
=> [QOLDEV-312] add support for CKAN 2.10 dashboard routing

ckanext/data_qld/helpers.py
- Only split on line break, not other whitespace
=> [QOLSVC-1879] fix parsing of resource format config

ckanext/data_qld/templates/package/read.html, ckanext/data_qld/templates/package/resource_read.html, ckanext/data_qld/templates/scheming/package/read.html, ckanext/data_qld/test_plugin.py
Truncation is already disabled on dataset pages, but we also need to disable it on resource pages.
=> QOLSVC-2447 don't truncate resource names

ckanext/data_qld/templates/scheming/form_snippets/upload.html
- The duplicate results in the server getting two values and squashing them into a list, which is bad
=> [QOLDEV-613] drop duplicate definition of 'url_type' input field

ckanext/data_qld/templates/base.html, ckanext/data_qld/templates/scheming/form_snippets/upload.html
Our template is unnecessarily adding a copy of the `url_type` field, which creates problems on CKAN 2.10.
=> Develop to master - drop duplicate 'url_type' field

ckanext/data_qld/fanstatic/data_qld.css
CKAN core developers are looking at changing the logout link into a button (see https://github.com/ckan/ckan/pull/7892), so we should adjust our styling to include that.
=> [QOLDEV-640] apply link styling to header buttons with the 'btn-link' class

ckanext/data_qld/templates/activity_streams/activity_stream_email_notifications.text
- Sync template with core to replace obsolete ungettext function and handle 'g' being absent"
- Convert email helper function to inline as helpers aren't available anymore in email context
=> [QOLSVC-4096] fix email notifications on CKAN 2.10

ckanext/data_qld/templates/activity_streams/activity_stream_email_notifications.text
The Python `reverse` function does not return a value, it reverses a list in place. The Jinja filter better matches what we want.
=> [QOLSVC-4096] use Jinja filter for list reversal

ckanext/data_qld/templates/header.html
- Replacing the block entirely makes us less forward-compatible
=> [QOLSVC-3914] reuse parent header block for not-logged-in content

.github/workflows/test.yml, ckanext/data_qld/plugin.py, dev-requirements.txt, test/features/data_usability_rating.feature, test/features/steps/steps.py, test/fixtures/csv_resource_with_schema.csv
Fix the integration between ckanext-data-qld and ckanext-qa so we can apply our custom resource scoring algorithm.
=> QOLDEV-915 fix usability rating for CSV resources with valid schemas

ckanext/data_qld/controller_functions.py, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/datarequests/close.html, ckanext/data_qld/templates/datarequests/comment.html, ckanext/data_qld/templates/datarequests/edit.html, ckanext/data_qld/templates/datarequests/new.html, ckanext/data_qld/templates/datarequests/show.html
The Data Requests plugin is dropping `c` to prepare for CKAN 2.11, we need to stop relying on it too.
=> [QOLDEV-1011] drop Pylons 'c' object from data request handling

ckanext/data_qld/tests/conftest.py, ckanext/data_qld/tests/test_api.py, ckanext/data_qld/tests/test_metadata.py, ckanext/data_qld/tests/test_reporting.py, ckanext/data_qld/tests/test_resource_visibility.py, ckanext/data_qld/tests/test_validation.py, ckanext/data_qld/tests/test_validators.py
- Drop 'user' and 'sysadmin' fixtures, just use standard CKAN test factories
- Drop unnecessary fields from dataset and resource fixtures, just keep essential defaults
- Inject schemas as fixtures where specifically needed instead of including in every test
- Cut unnecessary uploaded file in fixtures
=> [QOLDEV-1070] reduce usage of custom fixtures

requirements.txt
- This requirement creates problems if plugins are installed in reverse order. TODO Define plugin installation order in cookbook to ensure inter-plugin dependencies are handled.
=> [QOLDEV-1070] drop ckanext-harvest requirement

ckanext/data_qld/templates/datarequests/index.html, test/features/datarequest.feature
This was previously handled by overriding the template block.
=> [QOLSVC-9308] apply our custom display name to data request status

ckanext/data_qld/fanstatic/ga4_dataLayer_login.js, ckanext/data_qld/fanstatic/ga4_dataLayer_logout.js, ckanext/data_qld/fanstatic/webassets.yml, ckanext/data_qld/google_analytics/controller_functions.py, ckanext/data_qld/templates/user/dashboard_datasets.html
client_id pseudo randomness per day for better session tracking of long running api jobs, also flag if logged in on api call.
Trigger events for login (dashboard dataset view which is the default drop location post login).
Trigger event 'logged_out' for logout page finish
=> QOLSVC-10984 ga4 touch ups

ckanext/data_qld/resource_freshness/helpers/helpers.py
```
[ckan.lib.helpers] Route name "dataset_read" is deprecated and will be removed. Please update calls to use "dataset.read" instead
```
```
Traceback (most recent call last):
File "/mnt/local_data/ckan_venv/src/ckanext-data-qld/ckanext/data_qld/resource_freshness/helpers/helpers.py", line 156, in send_email_dataset_notification
subject = render(
File "/mnt/local_data/ckan_venv/src/ckan/ckan/lib/base.py", line 103, in render
_allow_caching()
File "/mnt/local_data/ckan_venv/src/ckan/ckan/lib/base.py", line 115, in _allow_caching
elif ('user' in g and g.user) or _is_valid_session_cookie_data():
File "/mnt/local_data/ckan_venv/lib64/python3.9/site-packages/werkzeug/local.py", line 318, in __get__
obj = instance._get_current_object()
File …
```
=> QOLDEV-979 update render to be able to run outside of flask as a task/job instead of inside the website runder engine
