qld-gov-au/ckanext-data-qld

ckanext/data_qld/auth_functions.py, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py
Adding back in open_datarequest auth function
=> Fixed user not logged in issues with checking access

ckanext/data_qld/actions.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/emails/bodies/close_datarequest_creator.txt, ckanext/data_qld/templates/emails/bodies/new_datarequest_organisation.txt, ckanext/data_qld/templates/emails/subjects/close_datarequest_creator.txt
override default close_datarequest action to only send new email template to the creator
=> Added new close datarequest email template 

.docker/test.ini, .env, .flake8, ckanext/__init__.py, ckanext/data_qld/actions.py, ckanext/data_qld/auth_functions.py, ckanext/data_qld/ckan_dataset.json, ckanext/data_qld/commands.py, ckanext/data_qld/controller.py, ckanext/data_qld/converters.py, ckanext/data_qld/google_analytics/__init__.py, ckanext/data_qld/google_analytics/capture_api_actions.json, ckanext/data_qld/google_analytics/controller.py, ckanext/data_qld/google_analytics/plugin.py, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/admin/config.html, ckanext/data_qld/tests/test_plugin.py, docker-compose.yml, test/features/homepage.feature
- Code was modified to pass PEP8 coding standard enforced by linter.
- Removed stale and debug comments.
=> Fixed coding standards.

README.md, ckanext/data_qld/ckan_dataset.json, ckanext/data_qld/commands.py
Added update frequency to dataset meta data schema
Update migration script to set default value for update frequency and removed expiration date
=> Removed next review date from resource meta data schema

ckanext/data_qld/auth_functions.py, ckanext/data_qld/plugin.py
This PR is for a proof-of-concept for dataset group assignment.
=> [DQL-88] Changes for POC group configuration.

.docker/Dockerfile.ckan, .docker/scripts/create-test-data.sh, .docker/scripts/init-ext.sh, .docker/scripts/init.sh, .docker/test.ini, ckanext/data_qld/ckan_dataset.json, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/presets.json, ckanext/data_qld/templates/admin/config.html, ckanext/data_qld/validation.py, requirements-dev.txt, test/features/config.feature, test/features/data_validation.feature, test/features/environment.py, test/features/schema_metadata.feature, test/features/steps/steps.py, test/fixtures/test-resource_schemea.json
This PR contains work for the following Jira stories:
- DQL-70 - Automated Tests - FR7 - Data Validation
- DQL-102 - FE - Change title size & fix lhs bar truncation
- DQL-118 - When a new resource is added it goes to the top of the list
- DQL-124 - Addition to Update frequency dropdown list
=> Training to develop

.docker/Dockerfile.ckan, .docker/scripts/create-test-data.sh, .docker/scripts/init-ext.sh, .docker/scripts/init.sh, .docker/test.ini, ckanext/data_qld/ckan_dataset.json, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/presets.json, ckanext/data_qld/templates/admin/config.html, ckanext/data_qld/validation.py, requirements-dev.txt, test/features/config.feature, test/features/data_validation.feature, test/features/environment.py, test/features/schema_metadata.feature, test/features/steps/steps.py, test/fixtures/test-resource_schemea.json
[QOL-5557] move 'Annually' frequency to its proper position
=> BDD Tests and minor updates

requirements-dev.txt, test/features/environment.py
- also ensure that we use newer Splinter since the new argument name won't work with an old one
=> [QOL-6375] update browser arguments for new Splinter

ckanext/data_qld/actions.py, ckanext/data_qld/auth_functions.py, ckanext/data_qld/datarequest_auth_functions.py, ckanext/data_qld/plugin.py
This will enable us to more easily reuse this plugin for the Publications theme.
=> [QOL-5834] gracefully handle missing DataRequests or Scheming extensions

ckanext/data_qld/actions.py, ckanext/data_qld/resources_plugin.py
- we need it for sending emails to admins
=> [DC-16134] ensure user list is included when loading org details

.docker/Dockerfile.ckan, .docker/scripts/create-test-data.sh, ckanext/data_qld/actions.py, ckanext/data_qld/commands.py, ckanext/data_qld/resources_plugin.py, docker-compose.yml, requirements-dev.txt, setup.py, test/features/environment.py, test/features/steps/steps.py
QOL-5710 should be re-tested first.
=> Develop to master

ckanext/data_qld/blueprint_overrides.py, ckanext/data_qld/controller.py, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/activity_streams/activity_stream_email_notifications.text, ckanext/data_qld/templates/emails/bodies/new_datarequest_organisation.txt, test/features/environment.py, test/features/login_redirect.feature, test/features/steps/steps.py
This PR contains changes for the following stories:
- [DQL2-18] Follow activity email notification enhancements
- [DQL2-20] Automated tests
- [DQL2-21] Follow activity login rules
@duttonw & @ThrawnCA for your review.
=> [DQL-183] Follow activity enhancements

ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/admin/config.html
PR contains changes for Jira story DQL2-3 Sysadmin Enhancements - Configurable profanity list
@duttonw & @ThrawnCA for review please.
=> [DQL2-3] Configurable profanity list

ckanext/data_qld/reporting/controller.py, ckanext/data_qld/reporting/helpers/helpers.py, ckanext/data_qld/reporting/logic/action/get.py
@duttonw & @ThrawnCA - addresses an issue across UTC/local datetime comparison for DB queries - for your review. Thanks.
=> [DQL2-28] Ensure DB data comparisons use UTC.

ckanext/data_qld/reporting/helpers/helpers.py, ckanext/data_qld/reporting/logic/action/get.py
@duttonw & @ThrawnCA for review/merging please.
=> [DQL2-38] Fix for comment highlighting helper.

.ahoy.yml, .docker/test.ini, test/features/data_usability_rating.feature, test/features/steps/steps.py
@duttonw @ThrawnCA Here is the PR for [DQL2-12] 5 Star rating system - Automated testing considerations
- Setup ckan job workers for QA BDD tests
- Added CKAN config for archiver and qa
- Added data usability rating BDD tests and resource files
=> [DQL2-12] 5 Star rating system - Automated testing considerations

ckanext/data_qld/plugin.py, ckanext/data_qld/reporting/logic/action/get.py, ckanext/data_qld/resource_format_openness_scores.json
- [DQL2-9] Added new custom score logic for: GEOTIFF, GDB, GPKG
- [DQL2-38] Fix date comparison for `datarequests` action query
- Added logic to check if QA plugin is enabled before importing QA
@duttonw & @ThrawnCA for review / merging please.
=> [DQL2-9] 5 Star rating system - Customise rules as per requirements

ckanext/data_qld/plugin.py
- [DQL2-63] Exclude (soft) deleted datasets from reporting queries.
@duttonw & @ThrawnCA for review please.
=> [DQL2-63] Reporting on deleted datasets

ckanext/data_qld/plugin.py, ckanext/data_qld/reporting/logic/action/get.py
@duttonw & @ThrawnCA for review please.
=> [DQL2-9] Consider non-open license in score overrides.

ckanext/data_qld/commands.py, ckanext/data_qld/controller.py, ckanext/data_qld/integration_plugin.py, ckanext/data_qld/plugin.py, ckanext/data_qld/resources_plugin.py, requirements.txt
- This is important so that we can use them separately
=> [QOL-5834] copy changes from combined plugin to split plugins

.docker/test.ini, ckanext/data_qld/fanstatic/flag-comment.js, ckanext/data_qld/templates/package/resource_read.html, requirements-dev.txt
Use GET instead of POST so we don't trip the CSRF filter.
=> QOL-7939 fix comment flagging

test/features/comments.feature, test/features/config.feature, test/features/data_qld_theme.feature, test/features/data_usability_rating.feature, test/features/dataset_deletion.feature, test/features/resource_availability.feature, test/features/resources.feature, test/features/schema_metadata.feature, test/features/steps/steps.py
Also sync BDD steps with infrastructure project
=> [DQL3-79] update resource_visible flag test value to 'FALSE' instead of 'NO'

ckanext/data_qld/google_analytics/controller_functions.py
Access Flask 'request.environ' instead of Pylons 'c.environ'
=> [QOL-7939] update Google Analytics plugin to fix access to environment variables

ckanext/data_qld/templates/group/snippets/group_item.html, ckanext/data_qld/templates/organization/snippets/organization_item.html, test/features/groups.feature, test/features/organisations.feature
- Don't add unwanted 'action=read' parameter under Flask
=> [QOL-8940] handle CKAN 2.9 in group read links

ckanext/data_qld/reporting/blueprints.py, test/features/admin_reporting.feature, test/features/steps/steps.py
Ensure that the export function actually returns the assembled Flask view.
=> DC-31542 fix failed report export

ckanext/data_qld/templates/reporting/snippets/closed_datarequest_metrics.html, test/features/engagement_reporting.feature
Fix incorrect syntax in reporting on data requests closed as "to be released later".
=> DC-31542 Fix closed data request report

.ahoy.yml, .docker/scripts/create-test-data.sh, ckanext/data_qld/templates/package/snippets/resource_item.html, test/features/datasets.feature
- Copy error-handling from core
=> [DC-31965] robustly handle absent tracking summary data

ckanext/data_qld/templates/robots.txt
This might need to be added for all environments including Prod, see https://ssq-qol.atlassian.net/browse/QOLDEV-271?focusedCommentId=260121
=> [QOLDEV-271] Add "User-agent: *" to robots.txt for all environments

ckanext/data_qld/templates/package/comment_list.html, extensions.txt
Comment add/edit now requires recaptcha.
=> QOLDEV-455 add recaptcha to comment list template

.docker/ckan.ini, ckanext/data_qld/templates/package/resource_read.html, ckanext/data_qld/templates/package/snippets/resource_item.html, test/features/resource_availability.feature
This test appears to have been overwritten during a merge.
=> [CHDEXCHAE-60] restore scenario test for 'Hidden' text on resources flagged not visible

.ahoy.yml, bin/create-test-data.sh, bin/init.sh, test/features/admin_reporting.feature, test/features/datarequest.feature, test/features/dataset_schema.feature, test/features/engagement_reporting.feature, test/features/environment.py, test/features/google_analytics.feature, test/features/groups.feature, test/features/resources.feature, test/features/users.feature
- create-test-data.sh has to be executed for every test run, so try to minimise or lazy-load the data
- Also run database init while CKAN is starting up, to save time.
=> [CHDEXCHAE-60] remove unnecessary test data

bin/build.sh, bin/create-test-data.sh, ckanext/data_qld/templates/package/snippets/resources.html, docker-compose.yml, extensions.txt, test/features/resources.feature, test/features/steps/steps.py
- Override resource sidebar to add 'title' to links, containing the full not-truncated name
=> [QOLSVC-2447] add tooltip on truncated resource nav links

ckanext/data_qld/plugin.py
- Searches are introducing unacceptable overhead, need to fix before re-introducing
=> [CHDEXCHAE-64] disable data request comment searches due to performance

.ahoy.yml, .github/workflows/test.yml, bin/build.sh, ckanext/data_qld/actions.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/emails/bodies/close_datarequest_creator.txt, ckanext/data_qld/templates/emails/bodies/new_datarequest_organisation.txt, ckanext/data_qld/templates/emails/bodies/open_datarequest_creator.txt, ckanext/data_qld/templates/emails/bodies/open_datarequest_organisation.txt, ckanext/data_qld/templates/emails/bodies/unassigned_datarequest_organisation.txt, ckanext/data_qld/tests/ytp_comments/test_datarequest_search.py, extensions.txt, test/features/comments.feature, test/features/data_usability_rating.feature, test/features/datarequest.feature, test/features/datasets.feature, test/features/engagement_reporting.feature, test/features/environment.py, test/features/organisations.feature, test/features/steps/steps.py
Data Request features should be in ckanext-data-qld as much as possible, not here.
=> QOLDEV-638 move data request throttling into ckanext-data-qld

.github/workflows/test.yml, ckanext/data_qld/converters.py, ckanext/data_qld/fanstatic/resource_file_upload.js
Field names have changed with CKAN 2.10, JavaScript needs to change to match them.
=> QOLSVC-3826 hide size field for uploaded resources

ckanext/data_qld/templates/user/edit_user_form.html
- Extend parent template now that it has enough blocks to support what we need to do
=> [QOLSVC-4096] update user edit template to fix email notifications field

ckanext/data_qld/ckan_dataset.json, ckanext/data_qld/resource_freshness/helpers/helpers.py, test/features/resource_freshness.feature
Add ability to have datasets that are only updated every 2 or 4 years.
=> [QOLSVC-6875] Add Biennially,Quadrennially to update_frequency list

ckanext/data_qld/templates/page.html
- Commit https://github.com/ckan/ckan/commit/f5e04e19806 changed the main tag from using 'role' to 'class', we need to incorporate this so that styles are properly applied to its content
=> [QOLSVC-8437] add 'main' class to the appropriate tag to match latest CKAN

ckanext/data_qld/templates/scheming/form_snippets/package_schema.html
- Snippet has been dropped, need to use 'asset' tag directly
=> [QOLDEV-1013] update Validation asset inclusion to match latest changes

.ahoy.yml, .docker/ckan.ini, ckanext/data_qld/geoscience_dataset.json, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/templates/package/search.html, ckanext/data_qld/templates/package/snippets/resources_list.html, ckanext/data_qld/templates/snippets/facet_list.html, ckanext/data_qld/templates/snippets/search_form.html, dev-requirements.txt, requirements.txt, test/features/search_facets.feature
- This is simpler than keeping them separate when the Harvester is so dependent on the theme
=> [QOLDEV-1014] merge Geoscience Harvester features into Data theme plugin

ckanext/data_qld/actions.py, ckanext/data_qld/harvester/harvester_facets.py, ckanext/data_qld/plugin.py, ckanext/data_qld/tests/conftest.py, test/features/data_qld_theme.feature
when
@tk.chained_action is used and @tk.side_effect_free is missing, it will Block GET requests.
=> QOLDEV-1135 Fix package search get + plugin tidyup

ckanext/data_qld/google_analytics/controller_functions.py, ckanext/data_qld/google_analytics/plugin.py, ckanext/data_qld/resource_freshness/helpers/helpers.py
- Update collection URL to new property
- Send events as JSON instead of URL-encoded
- Restructure event data to match GA4 spec
=> [QOLSVC-10984] update from GA360 to GA4

ckanext/data_qld/controller_functions.py, ckanext/data_qld/fanstatic/ga4_dataLayer_logout.js, ckanext/data_qld/fanstatic/webassets.yml, ckanext/data_qld/google_analytics/controller_functions.py, ckanext/data_qld/google_analytics/plugin.py, ckanext/data_qld/harvester/harvester_facets.py, ckanext/data_qld/helpers.py, ckanext/data_qld/plugin.py, ckanext/data_qld/reporting/controller_functions.py, ckanext/data_qld/reporting/helpers/export_helpers.py, ckanext/data_qld/reporting/helpers/helpers.py, ckanext/data_qld/reporting/logic/action/get.py, ckanext/data_qld/resource_freshness/helpers/helpers.py, ckanext/data_qld/templates/base.html, ckanext/data_qld/templates/page.html, ckanext/data_qld/templates/user/logout.html
* Split custom event to be standard page view + api call event
* API to send user_id hash for logged in users or missing if not set
* Javascript additions to send user_id for logged in page views
* Javascript to force notify on logged out page (send null user_id)
* Re organise client javascript/noscript into correct positions
Also includes flake8 fixes.
=> QOLSVC-10984 improvements on api tracking and user tracking hash for logged in user metrics

ckanext/data_qld/templates/robots.txt
fixes: https://github.com/qld-gov-au/ckan/issues/232
=> search bots, prod to not get stuck on facet mutations
